version: "3"
services:
  exercism:
    image: mrbarker/exercism-python:latest
    volumes:
      - ~/.gitconfig:/root/.gitconfig
      - ~/.vimrc:/root/.vimrc
      - ~/.vim:/root/.vim
      - ./.config/exercism:/root/.config/exercism
      - ./:/root/exercism
    tty: true
